/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:260080ab-089a-4006-995c-0c9d302d106c",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_iTob6znwc",
    "aws_user_pools_web_client_id": "4ra42k30cdt1ab4rmqq5rslr4i",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "eu-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "usersdb-dev",
            "region": "eu-west-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "userservices",
            "endpoint": "https://3778v56d2d.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        }
    ]
};


export default awsmobile;
